### ISSUE TITLE
The layout of the multiple-choice answer seems messed up

### ISSUE THREAD

**Issue by Kaminari84** [garyhsieh/harborbot#1]

**Comment by garyhsieh** [comment]
Which question? Like the one below? If so, what is it supposed to look like?
![image](https://user-images.githubusercontent.com/1438577/44014470-fe8b194e-9e80-11e8-9989-2e38e1c2cec9.png)

**Comment by garyhsieh** [comment]
So, like make the options wider?

**Comment by Kaminari84** [comment]
Yes, I think it should be a bit wider ideally
